config/routes.rb
AlfredMueller::Application.routes.draw do

  devise_for :users, :class_name => 'Cms::User'

  namespace :api do
    resources :real_estates, :only=>:index
  end

  namespace :cms do
    resource :dashboards
    resources :news_items, :except => :show

    resources :gallery_photos, :except => :show do
      post :sort, :on => :collection
    end

    resources :reference_projects, :except => :show do
      post :sort, :on => :collection
    end

    resources :real_estate_categories, only: :index

    resources :real_estates do
      get :copy, :on => :member
      resource :address
      resource :pricing, :except=>:destroy
      resource :figure, :except=>:destroy
      resource :information
      resources :media_assets, :only => :index
      resources :image_croppings
      resources :images, :except => :index
      resources :floor_plans, :except => :index
      resources :videos, :except => :index
      resources :documents, :except => :index
    end


    resources :jobs do
      post :sort, :on => :collection
    end

    resources :teasers do
      post :sort, :on => :collection
    end

    resources :pages do
      Brick::Base::TYPES.each do |type|
        resources "#{type}_bricks", :controller => :bricks, :type => type, :except => :index
      end

      post :sort, on: :collection
    end

    resources :employees
    resources :users
  end

  scope ':locale', locale: /#{I18n.available_locales.join('|')}/ do
    resources :real_estates, :only => [:index, :show] do
      resources :appointments, :only => [:new, :create]
      resources :handout_orders, :only => [:new, :create]
      resources :floorplans, :only => [:index, :show]

      get 'Printout_*name', to: 'handouts#show', as: :printout
      resource :handout, :only => :show do
        member do
          get 'footer'
        end
      end
      match '*name' => 'handouts#deprecated_route', :as => :object_documentation
    end
    resource :job_application, :only => [:new, :create]
    resource :contact, :only => [:new, :create]
    resources :news_items, :only => :index
    resources :reference_projects, :only => :index
  end

  scope ':locale' do
    match '/:name' => 'pages#show'
  end

  match '/eingabetool' => 'cms/dashboards#show'
  match '/cms' => 'cms/dashboards#show'

  root :to => 'homepage#index'

end

app/controllers/cms/addresses_controller.rb
class Cms::AddressesController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate

  load_resource :through => :real_estate, :singleton => true
  authorize_resource :through => :real_estate, :singleton => true, :except => :show

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to cms_real_estate_address_path(@real_estate), :alert => exception.message
  end


  def new
    @address = Address.new
    respond_with @address
  end

  def edit
  end

  def create
    @address.real_estate = @real_estate

    if @address.save
      redirect_to_step(next_step_after('address'))
    else
      render 'new'
    end
  end

  def update
    if @address.update_attributes(params[:address])
      redirect_to_step(next_step_after('address'))
    else
      render 'edit'
    end
  end

  def show
  end

end

app/controllers/cms/bricks_controller.rb
class Cms::BricksController < Cms::SecuredController

  before_filter :load_page
  respond_to :html

  authorize_resource Page
  rescue_from CanCan::AccessDenied do |err|
    redirect_to cms_dashboards_path, alert: err.message
  end

  def new
    @teasers = Teaser.where(:locale => @page.locale)
    @brick = @page.bricks.build({}, brick_from_type)
    respond_with @brick
  end

  def create
    @brick = @page.bricks.build(params[brick_name], brick_from_type)
    @brick.position = @page.bricks.size + 1

    if @brick.save
      redirect_to edit_cms_page_path(@page)
    else
      render 'new'
    end
  end

  def edit
    @teasers = Teaser.where(:locale => @page.locale)
    @brick = @page.bricks.find(params[:id])
    respond_with @brick
  end

  def update
    @brick = @page.bricks.find(params[:id])
    if @brick.update_attributes(params[brick_name])
      redirect_to edit_cms_page_path(@page)
    else
      render 'edit'
    end
  end

  def destroy
    brick = @page.bricks.find(params[:id])
    brick.destroy
    redirect_to edit_cms_page_path(@page)
  end

  private

  def load_page
    @page = Page.find(params[:page_id])
  end

  def brick_from_type type = nil
    type ||= params[:type]
    "brick/#{type}".classify.constantize
  end

  def brick_name
    "brick_#{params[:type]}".underscore.to_sym
  end
end

app/controllers/cms/dashboards_controller.rb
class Cms::DashboardsController < Cms::SecuredController

  respond_to :html

  def show
    review_count = RealEstate.in_review.recently_updated.count

    if review_count > 0 && current_user.admin?
      flash.now[:notice] = t('cms.dashboards.real_estates_for_review', :count => review_count)
    end

    @to_be_reviewed_real_estates = RealEstateDecorator.decorate(RealEstate.in_review.order([:updated_at, :desc]))
    @last_edited_real_estates = RealEstateDecorator.decorate(RealEstate.editing.order([:updated_at, :desc]).limit(5))
    @last_published_real_estates = RealEstateDecorator.decorate(RealEstate.published.order([:updated_at, :desc]).limit(5))
  end
end

app/controllers/cms/documents_controller.rb
class Cms::DocumentsController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate

  load_resource :class=>MediaAssets::Document, :through => :real_estate
  authorize_resource :class=>MediaAssets::Document, :through => :real_estate, :except => :show

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to cms_real_estate_media_assets_path(@real_estate), :alert => exception.message
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @document = @real_estate.documents.create(params[:document])
    respond_with @document, :location => cms_real_estate_media_assets_path
  end

  def update
    @document.update_attributes(params[:document])
    respond_with @document, :location => cms_real_estate_media_assets_path
  end

  def destroy
    @document.destroy
    redirect_to cms_real_estate_media_assets_path
  end
end

app/controllers/cms/employees_controller.rb
class Cms::EmployeesController < Cms::SecuredController
  respond_to :html
  authorize_resource

  rescue_from CanCan::AccessDenied do |err|
    redirect_to cms_dashboards_path, :alert => err.message
  end

  def index
    @employees = Employee.all.order([:lastname, :asc])
    respond_with @employees
  end

  def new
    @employee = Employee.new
    respond_with @employee
  end

  def create
    @employee = Employee.new(params[:employee])

    if @employee.save
      flash[:success] = t("cms.employees.create.success")
    end

    respond_with @employee, :location => [:cms, :employees]
  end

  def edit
    @employee = Employee.find(params[:id])
    respond_with @employee
  end

  def update
    @employee = Employee.find(params[:id])

    if @employee.update_attributes(params[:employee])
      flash[:success] = t("cms.employees.update.success")
    end

    respond_with @employee, :location => [:cms, :employees]
  end

  def destroy
    @employee = Employee.find(params[:id])
    if @employee.destroy
      flash[:success] = t("cms.employees.destroy.success")
    end
    redirect_to [:cms, :employees]
  end
end

app/controllers/cms/figures_controller.rb
class Cms::FiguresController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate

  load_resource :through => :real_estate, :singleton => true
  authorize_resource :through => :real_estate, :singleton => true, :except => :show

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to cms_real_estate_figure_path(@real_estate), :alert => exception.message
  end

  def new
  end

  def edit
  end

  def show
  end

  def create
    changed = update_html_inputs

    if @figure.save
      return render 'edit' if changed && !params[:force_redirect]
      redirect_to_step(next_step_after('figure'))
    else
      render 'new'
    end
  end

  def update
    @figure.attributes = params[:figure]
    changed = update_html_inputs

    if @figure.save && (!changed && !params[:force_redirect])
      redirect_to_step(next_step_after('figure'))
    else
      render 'edit'
    end
  end

  private
  def update_html_inputs
    @original_offer_html = @figure.offer_html.try(&:html_safe)

    decorator = FigureDecorator.new(@figure)
    @offer_html_changed = decorator.update_list_in(:offer)

    @offer_html_changed
  end
end

app/controllers/cms/floor_plans_controller.rb
class Cms::FloorPlansController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate

  load_resource :class => MediaAssets::FloorPlan, :through => :real_estate
  authorize_resource :class => MediaAssets::FloorPlan, :through => :real_estate, :except => :show

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to cms_real_estate_media_assets_path(@real_estate), :alert => exception.message
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @floor_plan = @real_estate.floor_plans.create(params[:floor_plan])
    if @floor_plan.valid?
      render :edit
    else
      render :new
    end
  end

  def update
    @floor_plan.update_attributes(params[:floor_plan])
    render :edit
  end

  def destroy
    @floor_plan.destroy
    redirect_to [:cms, @real_estate, :media_assets]
  end
end

app/controllers/cms/gallery_photos_controller.rb
# encoding: utf-8
#
module Cms
  class GalleryPhotosController < Cms::SecuredController

    authorize_resource

    rescue_from CanCan::AccessDenied do |err|
      redirect_to cms_dashboards_path, :alert => err.message
    end

    rescue_from Mongoid::Errors::DocumentNotFound do |err|
      flash[:warn] = "Gesuchtes Foto wurde nicht gefunden"
      redirect_to cms_gallery_photos_path
    end

    def index
      @gallery_photos = GalleryPhoto.all
      respond_with @gallery_photos
    end

    def new
      @gallery_photo = GalleryPhoto.new
      respond_with @gallery_photo
    end

    def create
      @gallery_photo = GalleryPhoto.new(params[:gallery_photo])

      if @gallery_photo.save
        flash[:success] = %(Das Foto "#{@gallery_photo.title}" wurde erfolgreich gespeichert.)
        redirect_to cms_gallery_photos_path
      else
        render 'new'
      end
    end

    def edit
      @gallery_photo = GalleryPhoto.find(params[:id])
      respond_with @gallery_photo
    end

    def update
      @gallery_photo = GalleryPhoto.find(params[:id])

      if @gallery_photo.update_attributes(params[:gallery_photo])
        flash[:succes] = %(Das Foto "#{@gallery_photo.title}" wurde erfolgreich gespeichert.)
        redirect_to cms_gallery_photos_path
      else
        render 'edit'
      end
    end

    def destroy
      gallery_photo = GalleryPhoto.find(params[:id])
      gallery_photo.destroy
      flash[:alert] = %(Das Foto "#{gallery_photo.title}" wurde erfolgreich gelöscht.)
      redirect_to cms_gallery_photos_path
    end

    def sort
      if params[:gallery_photos].present?
        params[:gallery_photos].each do |id_position_map|
          id_position_map.each do |id, position|
            GalleryPhoto.find(id).update_attributes!(:position => position[:position].to_i)
          end
        end
      end
      render :nothing => true
    end
  end
end

app/controllers/cms/image_croppings_controller.rb
class Cms::ImageCroppingsController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate
  
  respond_to :html
  
  rescue_from CanCan::AccessDenied do |err|
    redirect_to cms_dashboards_path
  end

  def edit
    if params[:image_type] == 'floor_plan'
      @image = @real_estate.floor_plans.find(params[:id])
    else
      @image = @real_estate.images.find(params[:id])
    end
    render :edit , locals: { image_type: params[:image_type] }
  end
end

app/controllers/cms/images_controller.rb
class Cms::ImagesController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate

  load_resource :class => MediaAssets::Image, :through => :real_estate
  authorize_resource :class => MediaAssets::Image, :through => :real_estate, :except => :show

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to cms_real_estate_media_assets_path(@real_estate), :alert => exception.message
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @image = @real_estate.images.create(params[:image])
    if @image.valid?
      render :edit
    else
      render :new
    end
  end

  def update
    @image.update_attributes(params[:image])
    render :edit
  end

  def destroy
    @image.destroy
    redirect_to [:cms, @real_estate, :media_assets]
  end
end

app/controllers/cms/information_controller.rb
class Cms::InformationController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate

  load_resource :through => :real_estate, :singleton => true
  authorize_resource :through => :real_estate, :singleton => true, :except => :show

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to cms_real_estate_information_path(@real_estate), :alert => exception.message
  end

  def new
    @information = Information.new
    @information.build_points_of_interest(@real_estate)
    respond_with @information
  end

  def edit
    @information.build_points_of_interest(@real_estate)
  end

  def create
    changed = update_html_inputs

    if @information.save
      return render 'edit' if changed
      redirect_to_step(next_step_after('information'))
    else
      render 'new'
    end
  end

  def update
    @information.attributes = params[:information]
    changed = update_html_inputs

    if @information.save && !changed
      redirect_to_step(next_step_after('information'))
    else
      render 'edit'
    end
  end

  def show
  end

  private
  def update_html_inputs
    @original_location_html = @information.location_html.try(&:html_safe)
    @original_infrastructure_html = @information.infrastructure_html.try(&:html_safe)
    @original_interior_html = @information.interior_html.try(&:html_safe)

    decorator = InformationDecorator.new(@information)
    @location_html_changed = decorator.update_list_in(:location)
    @infrastructure_html_changed = decorator.update_list_in(:infrastructure)
    @interior_html_changed = decorator.update_list_in(:interior)

    @infrastructure_html_changed || @location_html_changed || @interior_html_changed
  end
end

app/controllers/cms/jobs_controller.rb
# encoding: utf-8

class Cms::JobsController < Cms::SecuredController
  respond_to :html
  authorize_resource

  rescue_from CanCan::AccessDenied do |err|
    redirect_to cms_dashboards_path, :alert => err.message
  end

  def index
    @jobs = Job.where(:locale => content_locale).order([:updated_at, :desc])
    respond_with @jobs
  end

  def new
    @job = Job.new(:locale => content_locale)
    respond_with @job
  end

  def create
    @job = Job.new(params[:job])

    if @job.save
      flash[:success] = %(Der Job "#{@job.title}" wurde erfolgreich gespeichert.)
      redirect_to cms_jobs_path
    else
      render 'new'
    end
  end

  def edit
    @job = Job.find(params[:id])
    respond_with @job
  end

  def update
    @job = Job.find(params[:id])

    if @job.update_attributes(params[:job])
      flash[:success] = %(Der Job "#{@job.title}" wurde erfolgreich gespeichert.)
      redirect_to edit_cms_job_path(@job)
    else
      render 'edit'
    end
  end

  def destroy
    job = Job.find(params[:id])
    job.destroy
    flash[:alert] = %(Der Job "#{job.title}" wurde erfolgreich gelöscht.)
    redirect_to cms_jobs_path
  end

  def sort
    if params[:jobs].present?
      params[:jobs].each do |id_position_map|
        id_position_map.each do |id, position|
          Job.find(id).update_attributes!(:position => position[:position].to_i)
        end
      end
    end
    render :nothing => true
  end
end

app/controllers/cms/media_assets_controller.rb
class Cms::MediaAssetsController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate

  def index
  end
end

app/controllers/cms/pages_controller.rb
require 'page_tree'

class Cms::PagesController < Cms::SecuredController
  respond_to :html
  authorize_resource

  rescue_from CanCan::AccessDenied do |err|
    redirect_to cms_dashboards_path, alert: err.message
  end

  def index
    @pages = Page.roots.ordered_by_position.where(locale: content_locale).order([:updated, :asc])
    respond_with @pages
  end

  def new
    @page = Page.new(locale: content_locale, parent_id: params[:parent_id])
    respond_with @page
  end

  def create
    @page = Page.new(params[:page])
    if @page.save
      redirect_to edit_cms_page_path(@page)
    else
      render 'new'
    end
  end

  def edit
    @page = Page.find(params[:id])
    respond_with @page
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(params[:page])
      redirect_to edit_cms_page_path(@page)
    else
      render 'edit'
    end
  end

  def destroy
    page = Page.find(params[:id])
    page.destroy
    redirect_to cms_pages_path
  end

  def sort
    PageTree.update(params[:page_tree])
  end
end

app/controllers/cms/real_estate_categories_controller.rb
class Cms::RealEstateCategoriesController < ApplicationController
  def index
    @categories = Category.unscoped.where(utilization: params[:utilization]).sorted_by_utilization
    @category = @categories.first
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/cms/real_estate_utilizations_controller.rb
class Cms::RealEstateUtilizationsController < ApplicationController
  def index
    @categories = Category.unscoped.where(utilization: params[:utilization]).sorted_by_utilization

    respond_to do |format|
      format.js
    end
  end
end

app/views/cms/pricings/_form.html.haml
= render 'wizard_header'

= render_navigation :context => :real_estate

= form_for @pricing, :url => cms_real_estate_pricing_path(@real_estate) do |f|
  = render 'cms/shared/errors', :model => @pricing

  %fieldset.push-checkboxes-down
    %legend Preise
    .row
      .span6
        .control-group.mandatory
          = f.label :price_unit
          .controls
            - if PriceUnit.all_by_offer_and_utilization(@real_estate.offer, @real_estate.utilization).count > 1
              = f.select :price_unit, (PriceUnit.all_by_offer_and_utilization(@real_estate.offer, @real_estate.utilization)).map { |c| [t(".#{c}"), c] }, :include_blank => 'Preiseinheit auswählen'
            - else
              = f.hidden_field :price_unit, :value => PriceUnit.all_by_offer_and_utilization(@real_estate.offer, @real_estate.utilization).first
              %span.input-to-text= t(".#{PriceUnit.all_by_offer_and_utilization(@real_estate.offer, @real_estate.utilization).first}")

        - if @real_estate.for_rent?
          - if accessible?(:for_rent_netto)
            .control-group.mandatory
              = f.label :for_rent_netto, @real_estate.parking? ? t('mongoid.attributes.pricing.for_rent_netto_parking') : t('mongoid.attributes.pricing.for_rent_netto')
              .controls
                = f.text_field :for_rent_netto

        - if @real_estate.for_sale?
          .control-group.mandatory
            = f.label :for_sale
            .controls
              = f.text_field :for_sale

        - if accessible?(:estimate)
          .control-group
            = f.label :estimate
            .controls
              = f.text_field :estimate
              %i.icon-question-sign.help-popover{ :rel => 'popover', 'data-original-title' => Pricing.human_attribute_name(:estimate), 'data-content' => t('.help_popover.estimate') }

        - if accessible?(:additional_costs)
          .control-group{ :class => (@pricing.mandatory_for_rentable_parking? ? 'mandatory' : '') }
            = f.label :additional_costs
            .controls
              = f.text_field :additional_costs

        - if accessible?(:storage)
          .control-group
            = f.label :storage
            .controls
              = f.text_field :storage

        - if accessible?(:extra_storage)
          .control-group
            = f.label :extra_storage
            .controls
              = f.text_field :extra_storage

        - unless @real_estate.parking?
          - floated_field(f, :text_field, :inside_parking)
          - floated_field(f, :text_field, :outside_parking)
          - floated_field(f, :text_field, :covered_slot)
          - floated_field(f, :text_field, :covered_bike)
          - floated_field(f, :text_field, :outdoor_bike)
          - floated_field(f, :text_field, :single_garage)
          - floated_field(f, :text_field, :double_garage)

        .control-group
          = f.label :opted
          .controls
            = f.check_box :opted

      .span6.general.monthly-prices-container.hidden{ 'data-dependent_on' => '#pricing_price_unit', 'data-dependent_on_value' => 'year_m2' }
        .control-group.control-group-spacer

        .control-group.mandatory
          = f.label :for_rent_netto_monthly, t('mongoid.attributes.pricing.monthly')
          .controls
            = f.text_field :for_rent_netto_monthly

        .control-group
          = f.label :estimate_monthly, t('mongoid.attributes.pricing.monthly')
          .controls
            = f.text_field :estimate_monthly

        .control-group{ :class => (@pricing.mandatory_for_rentable_parking? ? 'mandatory' : '') }
          = f.label :additional_costs_monthly, t('mongoid.attributes.pricing.monthly')
          .controls
            = f.text_field :additional_costs_monthly

        - if accessible?(:storage)
          .control-group
            = f.label :storage_monthly, t('mongoid.attributes.pricing.monthly')
            .controls
              = f.text_field :storage_monthly

        - if accessible?(:extra_storage)
          .control-group
            = f.label :extra_storage_monthly, t('mongoid.attributes.pricing.monthly')
            .controls
              = f.text_field :extra_storage_monthly


  %fieldset
    %legend Bezug

    .control-group.mandatory
      = f.label :available_from
      .controls
        = f.date_select :available_from#, :start_year=>Date.today.year, :end_year=>5.years.from_now.year

    .control-group
      = f.label :display_estimated_available_from
      .controls
        = f.text_field :display_estimated_available_from
        %i.icon-question-sign.help-popover{ :rel => 'popover', 'data-original-title' => Pricing.human_attribute_name(:display_estimated_available_from), 'data-content' => t('.help_popover.display_estimated_available_from') }

  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = render 'cms/real_estates/actions'

app/views/cms/pricings/show.html.haml
= render 'wizard_header'

= render_navigation :context => :real_estate

%legend Preise
- if @real_estate.for_rent?
  .row
    .span5
      %dl.dl-horizontal
        %dt= t "mongoid.attributes.pricing.price_unit"
        %dd
          = t("cms.pricings.form.#{@pricing.price_unit}")

- if @real_estate.for_rent?
  - if accessible?(:for_rent_netto)
    .row
      .span5
        %dl.dl-horizontal
          %dt= @real_estate.parking? ? t("mongoid.attributes.pricing.for_rent_netto_parking") : t("mongoid.attributes.pricing.for_rent_netto")
          %dd
            = number_to_currency @pricing.for_rent_netto, :locale => 'de-CH'

      - if @pricing.price_unit_is_per_square_meter_per_year?
        .span5.monthly-prices-container
          %dl.dl-horizontal.dl-shrinked
            %dt= t("mongoid.attributes.pricing.monthly")
            %dd.for-rent-netto-monthly
              = number_to_currency @pricing.for_rent_netto_monthly, :locale => 'de-CH'

- if @real_estate.for_sale?
  .row
    .span5
      %dl.dl-horizontal
        %dt= t "mongoid.attributes.pricing.for_sale"
        %dd= number_to_currency @pricing.for_sale, :locale => 'de-CH'


- if accessible?(:estimate)
  .row
    .span5
      %dl.dl-horizontal
        %dt= t "mongoid.attributes.pricing.estimate"
        %dd
          = @pricing.estimate

    - if @pricing.price_unit_is_per_square_meter_per_year?
      .span5.monthly-prices-container
        %dl.dl-horizontal.dl-shrinked
          %dd.estimate-monthly= @pricing.estimate_monthly
          %dt= t "mongoid.attributes.pricing.monthly"

- if accessible?(:additional_costs)
  .row
    .span5
      %dl.dl-horizontal
        %dt= t "mongoid.attributes.pricing.additional_costs"
        %dd
          = number_to_currency @pricing.additional_costs, :locale => 'de-CH'

    - if @pricing.price_unit_is_per_square_meter_per_year?
      .span5.monthly-prices-container
        %dl.dl-horizontal.dl-shrinked
          %dt= t "mongoid.attributes.pricing.monthly"
          %dd.additional-costs-monthly
            = number_to_currency @pricing.additional_costs_monthly, :locale => 'de-CH'

.row
  .span5
    %dl.dl-horizontal
      - if accessible?(:extra_storage)
        %dt= t "mongoid.attributes.pricing.storage"
        %dd= number_to_currency @pricing.storage, :locale => 'de-CH'

  - if @pricing.price_unit_is_per_square_meter_per_year?
    .span5.monthly-prices-container
      %dl.dl-horizontal.dl-shrinked
        - if accessible?(:storage)
          %dt= t "mongoid.attributes.pricing.monthly"
          %dd.storage-monthly
            = number_to_currency @pricing.storage_monthly, :locale => 'de-CH'

.row
  .span5
    %dl.dl-horizontal
      - if accessible?(:extra_storage)
        %dt= t "mongoid.attributes.pricing.extra_storage"
        %dd
          = number_to_currency @pricing.extra_storage, :locale => 'de-CH'

  - if @pricing.price_unit_is_per_square_meter_per_year?
    .span5.monthly-prices-container
      %dl.dl-horizontal.dl-shrinked
        - if accessible?(:extra_storage)
          %dt= t "mongoid.attributes.pricing.monthly"
          %dd.extra-storage-monthly
            = number_to_currency @pricing.extra_storage_monthly, :locale => 'de-CH'

- unless @real_estate.parking?
  .row
    .span5
      %dl.dl-horizontal
        %dt= t "mongoid.attributes.pricing.inside_parking"
        %dd
          = number_to_currency @pricing.inside_parking, :locale => 'de-CH'
          &nbsp;
  .row
    .span5
      %dl.dl-horizontal
        %dt= t "mongoid.attributes.pricing.outside_parking"
        %dd
          = number_to_currency @pricing.outside_parking, :locale => 'de-CH'
          &nbsp;
  .row
    .span5
      %dl.dl-horizontal
        %dt= t "mongoid.attributes.pricing.covered_slot"
        %dd
          = number_to_currency @pricing.covered_slot, :locale => 'de-CH'
          &nbsp;
  .row
    .span5
      %dl.dl-horizontal
        %dt= t "mongoid.attributes.pricing.covered_bike"
        %dd
          = number_to_currency @pricing.covered_bike, :locale => 'de-CH'
          &nbsp;
  .row
    .span5
      %dl.dl-horizontal
        %dt= t "mongoid.attributes.pricing.outdoor_bike"
        %dd
          = number_to_currency @pricing.outdoor_bike, :locale => 'de-CH'
          &nbsp;
  .row
    .span5
      %dl.dl-horizontal
        %dt= t "mongoid.attributes.pricing.single_garage"
        %dd
          = number_to_currency @pricing.single_garage, :locale => 'de-CH'
          &nbsp;
  .row
    .span5
      %dl.dl-horizontal
        %dt= t "mongoid.attributes.pricing.double_garage"
        %dd
          = number_to_currency @pricing.double_garage, :locale => 'de-CH'
          &nbsp;
.row
  .span5
    %dl.dl-horizontal
      %dt= t "mongoid.attributes.pricing.opted"
      %dd= t "#{@pricing.opted}"


%legend Bezug
%dl.dl-horizontal
  %dt= t "mongoid.attributes.pricing.available_from"
  %dd
    = @pricing.available_from
    &nbsp;

  %dt= t "mongoid.attributes.pricing.display_estimated_available_from"
  %dd
    = @pricing.display_estimated_available_from
    &nbsp;