config/routes.rb
AlfredMueller::Application.routes.draw do

  devise_for :users, :class_name => 'Cms::User'

  namespace :api do
    resources :real_estates, :only=>:index
  end

  namespace :cms do
    resource :dashboards
    resources :news_items, :except => :show

    resources :gallery_photos, :except => :show do
      post :sort, :on => :collection
    end

    resources :reference_projects, :except => :show do
      post :sort, :on => :collection
    end

    resources :real_estate_categories, only: :index

    resources :real_estates do
      get :copy, :on => :member
      resource :address
      resource :pricing, :except=>:destroy
      resource :figure, :except=>:destroy
      resource :information
      resources :media_assets, :only => :index
      resources :image_croppings
      resources :images, :except => :index
      resources :floor_plans, :except => :index
      resources :videos, :except => :index
      resources :documents, :except => :index
    end


    resources :jobs do
      post :sort, :on => :collection
    end

    resources :teasers do
      post :sort, :on => :collection
    end

    resources :pages do
      Brick::Base::TYPES.each do |type|
        resources "#{type}_bricks", :controller => :bricks, :type => type, :except => :index
      end

      post :sort, on: :collection
    end

    resources :employees
    resources :users
  end

  scope ':locale', locale: /#{I18n.available_locales.join('|')}/ do
    resources :real_estates, :only => [:index, :show] do
      resources :appointments, :only => [:new, :create]
      resources :handout_orders, :only => [:new, :create]
      resources :floorplans, :only => [:index, :show]

      get 'Printout_*name', to: 'handouts#show', as: :printout
      resource :handout, :only => :show do
        member do
          get 'footer'
        end
      end
      match '*name' => 'handouts#deprecated_route', :as => :object_documentation
    end
    resource :job_application, :only => [:new, :create]
    resource :contact, :only => [:new, :create]
    resources :news_items, :only => :index
    resources :reference_projects, :only => :index
  end

  scope ':locale' do
    match '/:name' => 'pages#show'
  end

  match '/eingabetool' => 'cms/dashboards#show'
  match '/cms' => 'cms/dashboards#show'

  root :to => 'homepage#index'

end

app/controllers/cms/addresses_controller.rb
class Cms::AddressesController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate

  load_resource :through => :real_estate, :singleton => true
  authorize_resource :through => :real_estate, :singleton => true, :except => :show

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to cms_real_estate_address_path(@real_estate), :alert => exception.message
  end


  def new
    @address = Address.new
    respond_with @address
  end

  def edit
  end

  def create
    @address.real_estate = @real_estate

    if @address.save
      redirect_to_step(next_step_after('address'))
    else
      render 'new'
    end
  end

  def update
    if @address.update_attributes(params[:address])
      redirect_to_step(next_step_after('address'))
    else
      render 'edit'
    end
  end

  def show
  end

end

app/controllers/cms/bricks_controller.rb
class Cms::BricksController < Cms::SecuredController

  before_filter :load_page
  respond_to :html

  authorize_resource Page
  rescue_from CanCan::AccessDenied do |err|
    redirect_to cms_dashboards_path, alert: err.message
  end

  def new
    @teasers = Teaser.where(:locale => @page.locale)
    @brick = @page.bricks.build({}, brick_from_type)
    respond_with @brick
  end

  def create
    @brick = @page.bricks.build(params[brick_name], brick_from_type)
    @brick.position = @page.bricks.size + 1

    if @brick.save
      redirect_to edit_cms_page_path(@page)
    else
      render 'new'
    end
  end

  def edit
    @teasers = Teaser.where(:locale => @page.locale)
    @brick = @page.bricks.find(params[:id])
    respond_with @brick
  end

  def update
    @brick = @page.bricks.find(params[:id])
    if @brick.update_attributes(params[brick_name])
      redirect_to edit_cms_page_path(@page)
    else
      render 'edit'
    end
  end

  def destroy
    brick = @page.bricks.find(params[:id])
    brick.destroy
    redirect_to edit_cms_page_path(@page)
  end

  private

  def load_page
    @page = Page.find(params[:page_id])
  end

  def brick_from_type type = nil
    type ||= params[:type]
    "brick/#{type}".classify.constantize
  end

  def brick_name
    "brick_#{params[:type]}".underscore.to_sym
  end
end

app/controllers/cms/dashboards_controller.rb
class Cms::DashboardsController < Cms::SecuredController

  respond_to :html

  def show
    review_count = RealEstate.in_review.recently_updated.count

    if review_count > 0 && current_user.admin?
      flash.now[:notice] = t('cms.dashboards.real_estates_for_review', :count => review_count)
    end

    @to_be_reviewed_real_estates = RealEstateDecorator.decorate(RealEstate.in_review.order([:updated_at, :desc]))
    @last_edited_real_estates = RealEstateDecorator.decorate(RealEstate.editing.order([:updated_at, :desc]).limit(5))
    @last_published_real_estates = RealEstateDecorator.decorate(RealEstate.published.order([:updated_at, :desc]).limit(5))
  end
end

app/controllers/cms/documents_controller.rb
class Cms::DocumentsController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate

  load_resource :class=>MediaAssets::Document, :through => :real_estate
  authorize_resource :class=>MediaAssets::Document, :through => :real_estate, :except => :show

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to cms_real_estate_media_assets_path(@real_estate), :alert => exception.message
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @document = @real_estate.documents.create(params[:document])
    respond_with @document, :location => cms_real_estate_media_assets_path
  end

  def update
    @document.update_attributes(params[:document])
    respond_with @document, :location => cms_real_estate_media_assets_path
  end

  def destroy
    @document.destroy
    redirect_to cms_real_estate_media_assets_path
  end
end

app/controllers/cms/employees_controller.rb
class Cms::EmployeesController < Cms::SecuredController
  respond_to :html
  authorize_resource

  rescue_from CanCan::AccessDenied do |err|
    redirect_to cms_dashboards_path, :alert => err.message
  end

  def index
    @employees = Employee.all.order([:lastname, :asc])
    respond_with @employees
  end

  def new
    @employee = Employee.new
    respond_with @employee
  end

  def create
    @employee = Employee.new(params[:employee])

    if @employee.save
      flash[:success] = t("cms.employees.create.success")
    end

    respond_with @employee, :location => [:cms, :employees]
  end

  def edit
    @employee = Employee.find(params[:id])
    respond_with @employee
  end

  def update
    @employee = Employee.find(params[:id])

    if @employee.update_attributes(params[:employee])
      flash[:success] = t("cms.employees.update.success")
    end

    respond_with @employee, :location => [:cms, :employees]
  end

  def destroy
    @employee = Employee.find(params[:id])
    if @employee.destroy
      flash[:success] = t("cms.employees.destroy.success")
    end
    redirect_to [:cms, :employees]
  end
end

app/controllers/cms/figures_controller.rb
class Cms::FiguresController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate

  load_resource :through => :real_estate, :singleton => true
  authorize_resource :through => :real_estate, :singleton => true, :except => :show

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to cms_real_estate_figure_path(@real_estate), :alert => exception.message
  end

  def new
  end

  def edit
  end

  def show
  end

  def create
    changed = update_html_inputs

    if @figure.save
      return render 'edit' if changed && !params[:force_redirect]
      redirect_to_step(next_step_after('figure'))
    else
      render 'new'
    end
  end

  def update
    @figure.attributes = params[:figure]
    changed = update_html_inputs

    if @figure.save && (!changed && !params[:force_redirect])
      redirect_to_step(next_step_after('figure'))
    else
      render 'edit'
    end
  end

  private
  def update_html_inputs
    @original_offer_html = @figure.offer_html.try(&:html_safe)

    decorator = FigureDecorator.new(@figure)
    @offer_html_changed = decorator.update_list_in(:offer)

    @offer_html_changed
  end
end

app/controllers/cms/floor_plans_controller.rb
class Cms::FloorPlansController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate

  load_resource :class => MediaAssets::FloorPlan, :through => :real_estate
  authorize_resource :class => MediaAssets::FloorPlan, :through => :real_estate, :except => :show

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to cms_real_estate_media_assets_path(@real_estate), :alert => exception.message
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @floor_plan = @real_estate.floor_plans.create(params[:floor_plan])
    if @floor_plan.valid?
      render :edit
    else
      render :new
    end
  end

  def update
    @floor_plan.update_attributes(params[:floor_plan])
    render :edit
  end

  def destroy
    @floor_plan.destroy
    redirect_to [:cms, @real_estate, :media_assets]
  end
end

app/controllers/cms/gallery_photos_controller.rb
# encoding: utf-8
#
module Cms
  class GalleryPhotosController < Cms::SecuredController

    authorize_resource

    rescue_from CanCan::AccessDenied do |err|
      redirect_to cms_dashboards_path, :alert => err.message
    end

    rescue_from Mongoid::Errors::DocumentNotFound do |err|
      flash[:warn] = "Gesuchtes Foto wurde nicht gefunden"
      redirect_to cms_gallery_photos_path
    end

    def index
      @gallery_photos = GalleryPhoto.all
      respond_with @gallery_photos
    end

    def new
      @gallery_photo = GalleryPhoto.new
      respond_with @gallery_photo
    end

    def create
      @gallery_photo = GalleryPhoto.new(params[:gallery_photo])

      if @gallery_photo.save
        flash[:success] = %(Das Foto "#{@gallery_photo.title}" wurde erfolgreich gespeichert.)
        redirect_to cms_gallery_photos_path
      else
        render 'new'
      end
    end

    def edit
      @gallery_photo = GalleryPhoto.find(params[:id])
      respond_with @gallery_photo
    end

    def update
      @gallery_photo = GalleryPhoto.find(params[:id])

      if @gallery_photo.update_attributes(params[:gallery_photo])
        flash[:succes] = %(Das Foto "#{@gallery_photo.title}" wurde erfolgreich gespeichert.)
        redirect_to cms_gallery_photos_path
      else
        render 'edit'
      end
    end

    def destroy
      gallery_photo = GalleryPhoto.find(params[:id])
      gallery_photo.destroy
      flash[:alert] = %(Das Foto "#{gallery_photo.title}" wurde erfolgreich gelöscht.)
      redirect_to cms_gallery_photos_path
    end

    def sort
      if params[:gallery_photos].present?
        params[:gallery_photos].each do |id_position_map|
          id_position_map.each do |id, position|
            GalleryPhoto.find(id).update_attributes!(:position => position[:position].to_i)
          end
        end
      end
      render :nothing => true
    end
  end
end

app/controllers/cms/image_croppings_controller.rb
class Cms::ImageCroppingsController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate
  
  respond_to :html
  
  rescue_from CanCan::AccessDenied do |err|
    redirect_to cms_dashboards_path
  end

  def edit
    if params[:image_type] == 'floor_plan'
      @image = @real_estate.floor_plans.find(params[:id])
    else
      @image = @real_estate.images.find(params[:id])
    end
    render :edit , locals: { image_type: params[:image_type] }
  end
end

app/controllers/cms/images_controller.rb
class Cms::ImagesController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate

  load_resource :class => MediaAssets::Image, :through => :real_estate
  authorize_resource :class => MediaAssets::Image, :through => :real_estate, :except => :show

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to cms_real_estate_media_assets_path(@real_estate), :alert => exception.message
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @image = @real_estate.images.create(params[:image])
    if @image.valid?
      render :edit
    else
      render :new
    end
  end

  def update
    @image.update_attributes(params[:image])
    render :edit
  end

  def destroy
    @image.destroy
    redirect_to [:cms, @real_estate, :media_assets]
  end
end

app/controllers/cms/information_controller.rb
class Cms::InformationController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate

  load_resource :through => :real_estate, :singleton => true
  authorize_resource :through => :real_estate, :singleton => true, :except => :show

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to cms_real_estate_information_path(@real_estate), :alert => exception.message
  end

  def new
    @information = Information.new
    @information.build_points_of_interest(@real_estate)
    respond_with @information
  end

  def edit
    @information.build_points_of_interest(@real_estate)
  end

  def create
    changed = update_html_inputs

    if @information.save
      return render 'edit' if changed
      redirect_to_step(next_step_after('information'))
    else
      render 'new'
    end
  end

  def update
    @information.attributes = params[:information]
    changed = update_html_inputs

    if @information.save && !changed
      redirect_to_step(next_step_after('information'))
    else
      render 'edit'
    end
  end

  def show
  end

  private
  def update_html_inputs
    @original_location_html = @information.location_html.try(&:html_safe)
    @original_infrastructure_html = @information.infrastructure_html.try(&:html_safe)
    @original_interior_html = @information.interior_html.try(&:html_safe)

    decorator = InformationDecorator.new(@information)
    @location_html_changed = decorator.update_list_in(:location)
    @infrastructure_html_changed = decorator.update_list_in(:infrastructure)
    @interior_html_changed = decorator.update_list_in(:interior)

    @infrastructure_html_changed || @location_html_changed || @interior_html_changed
  end
end

app/controllers/cms/jobs_controller.rb
# encoding: utf-8

class Cms::JobsController < Cms::SecuredController
  respond_to :html
  authorize_resource

  rescue_from CanCan::AccessDenied do |err|
    redirect_to cms_dashboards_path, :alert => err.message
  end

  def index
    @jobs = Job.where(:locale => content_locale).order([:updated_at, :desc])
    respond_with @jobs
  end

  def new
    @job = Job.new(:locale => content_locale)
    respond_with @job
  end

  def create
    @job = Job.new(params[:job])

    if @job.save
      flash[:success] = %(Der Job "#{@job.title}" wurde erfolgreich gespeichert.)
      redirect_to cms_jobs_path
    else
      render 'new'
    end
  end

  def edit
    @job = Job.find(params[:id])
    respond_with @job
  end

  def update
    @job = Job.find(params[:id])

    if @job.update_attributes(params[:job])
      flash[:success] = %(Der Job "#{@job.title}" wurde erfolgreich gespeichert.)
      redirect_to edit_cms_job_path(@job)
    else
      render 'edit'
    end
  end

  def destroy
    job = Job.find(params[:id])
    job.destroy
    flash[:alert] = %(Der Job "#{job.title}" wurde erfolgreich gelöscht.)
    redirect_to cms_jobs_path
  end

  def sort
    if params[:jobs].present?
      params[:jobs].each do |id_position_map|
        id_position_map.each do |id, position|
          Job.find(id).update_attributes!(:position => position[:position].to_i)
        end
      end
    end
    render :nothing => true
  end
end

app/controllers/cms/media_assets_controller.rb
class Cms::MediaAssetsController < Cms::SecuredController
  include Concerns::EmbeddedInRealEstate

  def index
  end
end

app/controllers/cms/pages_controller.rb
require 'page_tree'

class Cms::PagesController < Cms::SecuredController
  respond_to :html
  authorize_resource

  rescue_from CanCan::AccessDenied do |err|
    redirect_to cms_dashboards_path, alert: err.message
  end

  def index
    @pages = Page.roots.ordered_by_position.where(locale: content_locale).order([:updated, :asc])
    respond_with @pages
  end

  def new
    @page = Page.new(locale: content_locale, parent_id: params[:parent_id])
    respond_with @page
  end

  def create
    @page = Page.new(params[:page])
    if @page.save
      redirect_to edit_cms_page_path(@page)
    else
      render 'new'
    end
  end

  def edit
    @page = Page.find(params[:id])
    respond_with @page
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(params[:page])
      redirect_to edit_cms_page_path(@page)
    else
      render 'edit'
    end
  end

  def destroy
    page = Page.find(params[:id])
    page.destroy
    redirect_to cms_pages_path
  end

  def sort
    PageTree.update(params[:page_tree])
  end
end

app/controllers/cms/real_estate_categories_controller.rb
class Cms::RealEstateCategoriesController < ApplicationController
  def index
    @categories = Category.unscoped.where(utilization: params[:utilization]).sorted_by_utilization
    @category = @categories.first
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/cms/real_estate_utilizations_controller.rb
class Cms::RealEstateUtilizationsController < ApplicationController
  def index
    @categories = Category.unscoped.where(utilization: params[:utilization]).sorted_by_utilization

    respond_to do |format|
      format.js
    end
  end
end

app/views/cms/reference_projects/_attachment_errors.html.haml
-if model.errors.any?
  .alert.alert-error.alert-block
    %ul
      - model.errors.full_messages.each do |msg|
        %li= msg

app/views/cms/reference_projects/_edit_images.html.haml
.row
  .span2
    %br
  .span8
    %table.table.table-bordered.images-table.sortable

      - if @reference_project.persisted?
        %thead
          %tr
            %th{ :width => '5%' }
            %th{ :width => '85%' } Bilder
            %th{ :width => '10%' } Löschen

        %tbody
          = f.fields_for :images do |image_form|
            = render 'attachment_errors', :model => image_form.object

            - unless image_form.object.errors.any?
              %tr.draggable-row{ :id => "image-#{image_form.object.id}" }
                %td.drag-handle{ :width => '5%' }
                  %i.icon-align-justify
                  = image_form.hidden_field :position
                %td{ :width => '85%' }
                  = image_tag image_form.object.image.thumb.url
                %td{ :width => '10%' }
                  = image_form.check_box :_destroy

        %tbody
          %tr
            %td
            %td{ :colspan => 2 }
              = f.fields_for :images, ReferenceProjectImage.new do |image_form|
                = image_form.file_field :image

      - else
        %thead
          %tr
            %th{ :width => '5%' }
            %th{ :colspan => 2, :width => '85%' } Bilder

        %tbody
          %tr
            %td
            %td{ :colspan => 2 }
              = f.fields_for :images, ReferenceProjectImage.new do |image_form|
                = image_form.file_field :image

app/views/cms/reference_projects/_form.html.haml
= form_for [:cms, @reference_project], :html => {:multipart => true} do |f|
  = render 'cms/shared/errors', :model => @reference_project

  %fieldset
    = f.hidden_field :locale
    .row
      .span12
        .control-group.mandatory
          = f.label :title
          .controls
            = f.text_field :title, :class => 'span8'

        .control-group
          = f.label :displayed_on
          - ReferenceProject::DISPLAYED_ON_PAGES.each do |page|
            .controls.push-inline-labels-down
              %label.inline.checkbox
                = check_box_tag "reference_project[displayed_on][]", page, @reference_project.displayed_on.include?(page), :class => page
                %span= t(".displayed_on.#{page}")

    .row.hidden{ 'data-dependent_on' => ".#{ReferenceProject::HOME_AND_OFFER_PAGE}", 'data-dependent_on_value' => 'true' }
      .span12
        %legend Startseiten-/Angebots-Slider
        .control-group.mandatory
          = f.label :offer
          .controls
            %label.inline.radio
              = f.radio_button :offer, Offer::RENT
              %span= t(".#{Offer::RENT}")
          .controls
            %label.inline.radio
              = f.radio_button :offer, Offer::SALE
              %span= t(".#{Offer::SALE}")

        .control-group.mandatory
          = f.label :utilization
          .controls
            %label.radio
              = f.radio_button :utilization, Utilization::LIVING
              %span= t(".#{Utilization::LIVING}")
            %label.radio
              = f.radio_button :utilization, Utilization::WORKING
              %span= t(".#{Utilization::WORKING}")

        .control-group
          = f.label :description
          .controls
            = f.text_area :description, :class => 'span8'

        .control-group
          = f.label :url
          .controls
            = f.text_field :url, :class => 'span8'

        .control-group
          = f.label :real_estate
          .controls
            = f.select :real_estate_id, @real_estates.collect {|p| [ p.title, p.id ]}, { :include_blank => true }

    .row.hidden{ 'data-dependent_on' => ".#{ReferenceProject::REFERENCE_PROJECT_PAGE}", 'data-dependent_on_value' => 'true' }
      .span12
        %legend Referenzseite
        .control-group.mandatory
          = f.label :section
          .controls
            = f.select :section, reference_project_sections

        .control-group
          = f.label :construction_info
          .controls
            = f.text_field :construction_info, :class => 'span8'

        .control-group
          = f.label :attachment
          .controls
            = f.file_field :attachment

            - if @reference_project.attachment.present?
              .well
                = f.hidden_field :attachment_cache
                %p
                  = link_to t('.show_attachment'), @reference_project.attachment.url, :target => '_blank'
                %label.inline
                  = f.check_box :remove_attachment
                  %span= t('.remove_attachment')

    .row
      .span12
        %legend Bilder
        = render "edit_images", :f => f

    .form-actions
      = f.submit nil, :class => 'btn btn-primary'
      .pull-right
        = link_to(cms_reference_projects_path, :class => 'btn small') do
          %i.icon-list
          = t('.overview')

app/views/cms/reference_projects/edit.html.haml
- content_for :title do
  Referenzprojekt bearbeiten

= render 'form'

app/views/cms/reference_projects/index.html.haml
- content_for :title do
  Erfasste Referenzprojekte

%ul.nav-tabs.nav.language-tabs
  - I18n.available_locales.each do |locale|
    %li{ :class => (content_locale.to_s == locale.to_s ? 'active' : nil) }
      = link_to t("languages.#{locale}"), cms_reference_projects_path(:content_locale => locale)

.row
  .pull-right.padded
    = link_to(new_cms_reference_project_path(:content_locale => content_locale), :class => 'btn') do
      %i.icon-plus-sign
      = t('.new')

- if @reference_projects.empty?
  .span4.offset4
    %h3.small
      Keine Einträge vorhanden
- else
  = form_for :reference_projects, :model => reference_projects, :url => sort_cms_reference_projects_path, :remote => true, :html => { :class => :autosubmit } do |form|
    %table.table.table-bordered.table-striped.reference-projects.reference-projects-sortable
      %thead
        %tr
          %th
          %th= ReferenceProject.human_attribute_name :title
          %th= ReferenceProject.human_attribute_name :offer
          %th= ReferenceProject.human_attribute_name :utilization
          %th.fixed-width= ReferenceProject.human_attribute_name :displayed_on
          %th
          %th

      %tbody
        - @reference_projects.each do |reference_project|
          %tr.reference-project.draggable-row{ :id => "reference_project_#{reference_project.id}"}
            %td.drag-handle{ :width => '5%' }
              %i.icon-align-justify
              = form.fields_for :[], reference_project do |reference_project_fields|
                = reference_project_fields.hidden_field :position, :class => 'position'
            %td.title= reference_project.title
            %td= t("real_estates.search_filter.#{reference_project.offer}")
            %td= t("real_estates.search_filter.#{reference_project.utilization}")
            %td
              - reference_project.displayed_on.each do |page|
                %span= t("cms.reference_projects.index.displayed_on.#{page}_html")
            %td= link_to  t('.destroy'), cms_reference_project_path(reference_project), :method => :delete, :confirm => t('.confirm_delete', :title => reference_project.title)
            %td= link_to t('.edit'), edit_cms_reference_project_path(reference_project)

  - content_for :javascripts do
    :coffeescript
      $ ->
        $("table.reference-projects-sortable tbody").sortable
          handle: ".drag-handle"
          update: (event, ui) ->
            tr = $(event.target).closest('tr.reference-project')
            tr.closest('table').find(".draggable-row").each (idx, elem) ->
              $(@).find(".position").val(idx+1)
            tr.closest('form.autosubmit').submit()

app/views/cms/reference_projects/new.html.haml
- content_for :title do
  Referenzprojekt in #{t("languages.#{@reference_project.locale}")} anlegen

= render 'form'