config/routes.rb
AlfredMueller::Application.routes.draw do

  devise_for :users, :class_name => 'Cms::User'

  namespace :api do
    resources :real_estates, :only=>:index
  end

  namespace :cms do
    resource :dashboards
    resources :news_items, :except => :show

    resources :gallery_photos, :except => :show do
      post :sort, :on => :collection
    end

    resources :reference_projects, :except => :show do
      post :sort, :on => :collection
    end

    resources :real_estate_categories, only: :index

    resources :real_estates do
      get :copy, :on => :member
      resource :address
      resource :pricing, :except=>:destroy
      resource :figure, :except=>:destroy
      resource :information
      resources :media_assets, :only => :index
      resources :image_croppings
      resources :images, :except => :index
      resources :floor_plans, :except => :index
      resources :videos, :except => :index
      resources :documents, :except => :index
    end


    resources :jobs do
      post :sort, :on => :collection
    end

    resources :teasers do
      post :sort, :on => :collection
    end

    resources :pages do
      Brick::Base::TYPES.each do |type|
        resources "#{type}_bricks", :controller => :bricks, :type => type, :except => :index
      end

      post :sort, on: :collection
    end

    resources :employees
    resources :users
  end

  scope ':locale', locale: /#{I18n.available_locales.join('|')}/ do
    resources :real_estates, :only => [:index, :show] do
      resources :appointments, :only => [:new, :create]
      resources :handout_orders, :only => [:new, :create]
      resources :floorplans, :only => [:index, :show]

      get 'Printout_*name', to: 'handouts#show', as: :printout
      resource :handout, :only => :show do
        member do
          get 'footer'
        end
      end
      match '*name' => 'handouts#deprecated_route', :as => :object_documentation
    end
    resource :job_application, :only => [:new, :create]
    resource :contact, :only => [:new, :create]
    resources :news_items, :only => :index
    resources :reference_projects, :only => :index
  end

  scope ':locale' do
    match '/:name' => 'pages#show'
  end

  match '/eingabetool' => 'cms/dashboards#show'
  match '/cms' => 'cms/dashboards#show'

  root :to => 'homepage#index'

end

app/models/brick/accordion.rb
class Brick::Accordion < Brick::Base
  field :title, :type => String
  field :text, :type => String

  validates :title, :presence => true
  validates :text, :presence => true

  def group_id
    if prev.present? && prev.type == 'accordion'
      prev.group_id.to_s.to_sym
    else
      id.to_s.to_sym
    end
  end
end

app/models/brick/base.rb
class Brick::Base
  include Mongoid::Document
  include Mongoid::Timestamps

  TYPES = %w(title text accordion placeholder download teaser)

  embedded_in :page
  default_scope asc(:position)
  before_create :setup_position

  field :position, :type => Integer

  def type
    _type.underscore.split('/').last
  end

  def prev
    idx = _parent.bricks.map(&:id).index(id)
    if idx - 1 >= 0
      _parent.bricks.to_a[idx - 1]
    else
      nil
    end
  end

  def next
    idx = _parent.bricks.map(&:id).index(id)
    _parent.bricks.to_a[idx + 1] rescue nil
  end

  private

  def setup_position
    self.position ||= _parent.bricks.max(:position).to_i + 1
  end
end

app/models/brick/download.rb
class Brick::Download < Brick::Base
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :file, type: String

  validates :title, presence: true
  validates :file, presence: true

  mount_uploader :file, DownloadBrickDocumentUploader
  mount_uploader :image, DownloadBrickImageUploader
end

app/models/brick/placeholder.rb
class Brick::Placeholder < Brick::Base

  TYPES = %w(jobs_openings jobs_apply_with_success job_profile_slider contact_form company_header)

  field :placeholder, :type => String

  validates :placeholder, :presence => true
end

app/models/brick/teaser.rb
class Brick::Teaser < Brick::Base
  belongs_to :teaser_1, class_name: 'Teaser'
  belongs_to :teaser_2, class_name: 'Teaser'
  belongs_to :teaser_3, class_name: 'Teaser'
  belongs_to :teaser_4, class_name: 'Teaser'
end

app/models/brick/text.rb
class Brick::Text < Brick::Base
  field :text, :type => String
  field :more_text, :type => String

  validates :text, :presence => true
end

app/models/brick/title.rb
class Brick::Title < Brick::Base
  field :title, :type => String

  validates :title, :presence => true

  def is_primary?
    first_brick = _parent.bricks.where(:_type => self.class.to_s).first
    first_brick == self
  end
end

app/controllers/cms/bricks_controller.rb
class Cms::BricksController < Cms::SecuredController

  before_filter :load_page
  respond_to :html

  authorize_resource Page
  rescue_from CanCan::AccessDenied do |err|
    redirect_to cms_dashboards_path, alert: err.message
  end

  def new
    @teasers = Teaser.where(:locale => @page.locale)
    @brick = @page.bricks.build({}, brick_from_type)
    respond_with @brick
  end

  def create
    @brick = @page.bricks.build(params[brick_name], brick_from_type)
    @brick.position = @page.bricks.size + 1

    if @brick.save
      redirect_to edit_cms_page_path(@page)
    else
      render 'new'
    end
  end

  def edit
    @teasers = Teaser.where(:locale => @page.locale)
    @brick = @page.bricks.find(params[:id])
    respond_with @brick
  end

  def update
    @brick = @page.bricks.find(params[:id])
    if @brick.update_attributes(params[brick_name])
      redirect_to edit_cms_page_path(@page)
    else
      render 'edit'
    end
  end

  def destroy
    brick = @page.bricks.find(params[:id])
    brick.destroy
    redirect_to edit_cms_page_path(@page)
  end

  private

  def load_page
    @page = Page.find(params[:page_id])
  end

  def brick_from_type type = nil
    type ||= params[:type]
    "brick/#{type}".classify.constantize
  end

  def brick_name
    "brick_#{params[:type]}".underscore.to_sym
  end
end

app/views/bricks/placeholder/_company_header.html.haml
%section#head-of-alfred-mueller-gallery.tab-slider
  %nav.button-navigation-container
    %ul.first-level-navigation.button-navigation
      %li
        %a.active{ :href => '#vision' }=t('.vision')
      %li
        %a{ :href => '#board-of-directors' }=t('.board_of_directors')
      %li
        %a{ :href => '#managing-board' }=t('.managing_board')
      %li
        %a{ :href => '#subsidiaries' }=t('.subsidiaries')

  %section.flex-container.hidden#vision.tab-content
    %h1.hidden=t('.vision')
    .flexslider
      %ul.slides
        %li
          = render 'partials/image_movie'

  %section.flex-container.hidden#board-of-directors.tab-content
    %h1.hidden=t('.board_of_directors')
    .flexslider
      %ul.second-level-navigation
        %li
          %a{ :href => '#' } Christoph Müller
        %li
          %a{ :href => '#' } Viktor Naumann
        %li
          %a{ :href => '#' } Adrian R. Bult
        %li
          %a{ :href => '#' } Ida M. Hardegger
        %li
          %a{ :href => '#' } Ulrich H. Moser
        %li
          %a{ :href => '#' } Erich Rüegg
        %li
          %a{ :href => '#' } Thomas Rüppel
        %li
          %a{ :href => '#' } Alfred Müller

      %ul.slides
        %li
          = image_tag 'head_of_alfred_mueller/board_of_directors/Christoph_Mueller.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              Christoph Müller
            %p
              = t('.president_of_board_of_directors')
            %p
              %a{ :href => 'mailto:christoph.mueller@alfred-mueller.ch' }
                =t('.mailto_text')
        %li
          = image_tag 'head_of_alfred_mueller/board_of_directors/Viktor_Naumann.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              Viktor Naumann
            %p
              = t('.vice_president_of_board_of_directors')
        %li
          = image_tag 'head_of_alfred_mueller/board_of_directors/Adrian_Bult.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              Adrian R. Bult
            %p
              = t('.member_of_board_of_directors')
        %li
          = image_tag 'head_of_alfred_mueller/board_of_directors/Ida_Hardegger.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              Ida M. Hardegger
            %p
              = t('.member_of_board_of_directors')
        %li
          = image_tag 'head_of_alfred_mueller/board_of_directors/Ulrich_Moser.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              Ulrich H. Moser
            %p
              = t('.member_of_board_of_directors')
        %li
          = image_tag 'head_of_alfred_mueller/board_of_directors/Dr_Erich_Rueegg.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              Erich Rüegg
            %p
              = t('.member_of_board_of_directors')
        %li
          = image_tag 'head_of_alfred_mueller/board_of_directors/Thomas_Rueppel.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              Thomas Rüppel
            %p
              = t('.member_of_board_of_directors')
        %li
          = image_tag 'head_of_alfred_mueller/board_of_directors/Alfred_Mueller.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              Alfred Müller
            %p
              = t('.honorary_president')

  %section.flex-container.hidden#managing-board.tab-content
    %h1.hidden=t('.managing_board')
    .flexslider
      %ul.second-level-navigation
        %li
          %a{ :href => '#' } David Hossli
        %li
          %a{ :href => '#' } Joe Schmalz
        %li
          %a{ :href => '#' } Michael Müller
        %li
          %a{ :href => '#' } Walter Hochreutener
        %li
          %a{ :href => '#' } Beat Stocker
        %li
          %a{ :href => '#' } François Bernath

      %ul.slides
        %li
          = image_tag 'head_of_alfred_mueller/managing_board/David_Hossli.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              David Hossli
            %p
              =t('.chairman_of_managing_board')
            %p
              %a{ :href => 'mailto:david.hossli@alfred-mueller.ch' }
                =t('.mailto_text')
        %li
          = image_tag 'head_of_alfred_mueller/managing_board/Joe_Schmalz.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              Joe Schmalz
            %p
              =t('.chief_financial_officer')
            %p
              %a{ :href => 'mailto:joe.schmalz@alfred-mueller.ch' }
                =t('.mailto_text')
        %li
          = image_tag 'head_of_alfred_mueller/managing_board/Michael_Mueller.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              Michael Müller
            %p
              =t('.head_of_portfolio')
            %p
              %a{ :href => 'mailto:michael.mueller@alfred-mueller.ch' }
                =t('.mailto_text')
        %li
          = image_tag 'head_of_alfred_mueller/managing_board/Walter_Hochreutener.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              Walter Hochreutener
            %p
              =t('.head_of_real_estate_management')
            %p
              %a{ :href => 'mailto:walter.hochreutener@alfred-mueller.ch' }
                =t('.mailto_text')
        %li
          = image_tag 'head_of_alfred_mueller/managing_board/Beat_Stocker.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              Beat Stocker
            %p
              =t('.head_development_and_general_contracting')
            %p
              %a{ :href => 'mailto:beat.stocker@alfred-mueller.ch' }
                =t('.mailto_text')
        %li
          = image_tag 'head_of_alfred_mueller/managing_board/Francois_Bernath.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              François Bernath
            %p
              =t('.head_department_acquisition_sales_and_marketing')
            %p
              %a{ :href => 'mailto:francois.bernath@alfred-mueller.ch' }
                =t('.mailto_text')

  %section.flex-container.hidden#subsidiaries.tab-content
    %h1.hidden=t('.subsidiaries')
    .flexslider
      %ul.second-level-navigation
        %li
          %a{ :href => '#' } Pierre El Soda
        %li
          %a{ :href => '#' } Massimiliano Paganini

      %ul.slides
        %li
          = image_tag 'head_of_alfred_mueller/branch/Pierre_El_Soda.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              Pierre El Soda
            %p
              = t('.director_of_subsidiary_western_switzerland')
            %p
              %a{ :href => 'mailto:pierre.elsoda@alfred-mueller.ch' }
                =t('.mailto_text')
        %li
          = image_tag 'head_of_alfred_mueller/branch/Massimiliano_Paganini.jpg'
          .tab-slider-description
            %strong.h1.tab-slider__title
              Massimiliano Paganini
            %p
              = t('.director_of_subsidiary_southern_switzerland')
            %p
              %a{ :href => 'mailto:massimiliano.paganini@alfred-mueller.ch' }
                =t('.mailto_text')

app/views/bricks/placeholder/_contact_form.html.haml
.contact-box
  .image{ :class => "image-for-contact-form-#{I18n.locale}"}
    .image-caption
      .image-caption-text
        %h3= t('.title')
        %p
          = t('.person_html')
        %p
          = t('.address_html')
      .clear
  .accordion.accordion--square
    .accordion__item
      = link_to t('.form_title'), new_contact_path, :remote => true, :class => :title
      .accordion__content.content
        #contact

app/views/bricks/placeholder/_job_profile_slider.html.haml
.tab-slider
  .button-navigation-container
    %ul.first-level-navigation.button-navigation
      %li
        %a.active{ :href => '#building-site-manager' } Bauleiter
      %li
        %a{ :href => '#real-estate-manager' } Immobilienverwalterin

  .flex-container.tab-content#building-site-manager
    %video#bulding-site-manager-movie.sublime{ title: 'Jobs: Bauleiter', poster: '/movies/bauleiter.png', width: '100%', height: '100%', preload: 'preload' }
      %source{ :src => '/movies/alfred_mueller_bauleiter.mp4' }

  .flex-container.hidden.tab-content#real-estate-manager
    %video#real-estate-manager-movie.sublime{ title: 'Jobs: Immobilienverwalterin', :poster => '/movies/immobilienverwalterin.png', :width => '100%', :height => '100%', :preload => 'preload' }
      %source{ :src => '/movies/alfred_mueller_immobilienverwalterin.mp4' }

app/views/bricks/placeholder/_jobs_apply_with_success.html.haml
.contact-box
  .image{ :class => "image-for-job-application-#{I18n.locale}" }
    .image-caption
      .image-caption-text#apply
        %strong.h3= t('.title')
        %p
          = t('.person_html')
        %p
          = link_to t('.address_text'), t('.address_link'), class: 'ga-tracking-link', data: { 'ga-category' => "Mitarbeiter", 'ga-action' => "Anzahl HR-Kontakte" }
      .clear
  .accordion.accordion--square
    .accordion__item
      = link_to t('.apply'), new_job_application_path, :remote => true, :class => :title
      .accordion__content.content
        #job-application

app/views/bricks/placeholder/_jobs_openings.html.haml
.jobs
  .accordion.accordion--square
    - Job.published.where(:locale => I18n.locale).each do |job|
      .accordion__item.accordion-ga-tracking-link{ :id => "job_#{job.id}", data: { 'ga-category' => "Mitarbeiter", 'ga-action' => "Ansicht Jobs", 'ga-label' => job.title } }
        .accordion__title
          %h3= job.title
        .accordion__content.content
          = job.text.html_safe
          %ul.icon-list
            - if job.job_profile_file.present?
              %li
                = link_to t('.download_pdf'), job.job_profile_file.url, :target => '_new', :class => 'icon-pdf-white'
            %li
              = link_to t('.recommend_job'), "mailto:?subject=#{t('.recommend_job_title')}&body=#{URI.encode(request.url)}#job_#{job.id}", :class => 'icon-mail-white'
            %li
              = link_to t('.apply_for_job'), '#apply', :class => 'icon-pen-white'